name: 'Setup various CI dependencies'
description: 'Setup Rust target and necessary dependencies for compilation'
inputs:
  target:
    description: 'rust target being set up'
    required: true
  emscripten_sdk:
    description: 'emsdk version to install'
    default: latest

runs:
  using: composite
  steps:
    - uses: dtolnay/rust-toolchain@stable
      with:
        target: ${{ inputs.target }}
    - run: echo "CARGO_BUILD_TARGET=${{ inputs.target }}" >> $GITHUB_ENV
      shell: bash

    - name: Install GCC (i686-unknown-linux-gnu)
      if: ${{ inputs.target == 'i686-unknown-linux-gnu' }}
      run: |
        sudo apt-get update -y
        sudo apt-get install -y --no-install-recommends gcc-multilib g++-multilib
      shell: bash
    - name: Install GCC (aarch64-unknown-linux-gnu)
      if: ${{ inputs.target == 'aarch64-unknown-linux-gnu' }}
      run: |
        sudo apt-get update -y
        sudo apt-get install -y --no-install-recommends gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libc6-dev-arm64-cross
      shell: bash

    - name: Install emscripten (wasm32-unknown-emscripten)
      if: ${{ inputs.target == 'wasm32-unknown-emscripten' }}
      run: |
        EM_CONFIG=$HOME/emsdk/.emscripten
        echo "EM_CONFIG=$EM_CONFIG" >> $GITHUB_ENV
        curl -L -o ~/emsdk-main.tar.gz https://github.com/emscripten-core/emsdk/archive/main.tar.gz
        tar -C ~ -xf ~/emsdk-main.tar.gz
        mv ~/emsdk-main ~/emsdk
        cd ~/emsdk
        ./emsdk install ${{ inputs.emscripten_sdk }}
        ./emsdk activate ${{ inputs.emscripten_sdk }}
        source ./emsdk_env.sh
        echo "EMSDK=$EMSDK" >> $GITHUB_ENV
        echo "EMSDK_NODE=$EMSDK_NODE" >> $GITHUB_ENV
        echo "CC_wasm32_unknown_emscripten=$EMSDK/upstream/emscripten/emcc" >> $GITHUB_ENV
        echo "CXX_wasm32_unknown_emscripten=$EMSDK/upstream/emscripten/em++" >> $GITHUB_ENV
        echo "AR_wasm32_unknown_emscripten=$EMSDK/upstream/emscripten/emar" >> $GITHUB_ENV
        echo "CARGO_TARGET_WASM32_UNKNOWN_EMSCRIPTEN_LINKER=$EMSDK/upstream/emscripten/emcc" >> $GITHUB_ENV
        echo "CARGO_TARGET_WASM32_UNKNOWN_EMSCRIPTEN_RUNNER=$EMSDK_NODE" >> $GITHUB_ENV
      shell: bash
